server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # 처음 table 만들 때는 create 나중에는 update로 수정한다
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 변수명 그대로 db에 필드를 만듬
      use-new-id-generator-mappings: false #jpa의 기본 numbering 전략을 따라가지 않음
    show-sql: true # 실행 sql 콘솔창 출력
    properties:
      hibernate.format_sql: true # sql 콘솔창 출력을 format에 맞게 나온다

  jackson:
    serialization:
      fail-on-empty-beans: false